spring.application.name=emc-lab-233009
spring.profiles.active=dev
app.stats.mv.refresh-ms=60000
spring.jpa.hibernate.ddl-auto=create

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer
